# name: Terraform CI/CD

# #main브랜치에 push 또는 PR이 생성되면 자동으로 실행
# on:
#   push:
#     branches:
#       - main
#   pull_request:
#     branches:
#       - main

# jobs:
#   terraform:
#     name: "Security Check, and Deploy"
#     runs-on: ubuntu-latest

#     env:
#       AWS_REGION: "ap-northeast-2"
#       TF_VERSION: "1.4.0"
#     # TFSEC_VERSION: "1.28.1" # Updated to a more recent version

#     steps:
#       - name: "Checkout GitHub repository"
#         uses: actions/checkout@v2

#       - name: "Configure AWS credentials"
#         uses: aws-actions/configure-aws-credentials@v1
#         with:
#           role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
#           aws-region: ${{ secrets.AWS_REGION }}

#       # terraform 설치 및 초기화
#       - name: "Set up Terraform"
#         uses: hashicorp/setup-terraform@v1
#         with:
#           terraform_version: ${{ env.TF_VERSION }}

#       #Trivy 설치 및 실행
#       - name: Install Trivy
#         run: |
#           curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin

#       - name: Run Trivy IaC Scan
#         run: trivy config .

#       #   - name: "Install tfsec"
#       #     run: |
#       #       curl -sLo tfsec https://github.com/aquasecurity/tfsec/releases/download/v${{ env.TFSEC_VERSION }}/tfsec-linux-amd64
#       #       chmod +x tfsec
#       #       mv tfsec /usr/local/bin/
#       #       tfsec --version

#       - name: "Terraform Init"
#         run: terraform init

#       - name: "Terraform Format"
#         run: terraform fmt

#       - name: "Terraform Validate"
#         run: terraform validate

#       #   - name: "tfsec"
#       #     run: tfsec .

#       - name: "Terraform Plan"
#         run: terraform plan -out=tfplan

#       - name: "Terraform Apply"
#         if: github.ref == 'refs/heads/main'
#         run: terraform apply -auto-approve tfplan
name: OIDC Test
on:
  push:
  workflow_dispatch:

permissions:
  id-token: write

jobs:
  access-s3:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-region: ap-northeast-2
          role-to-assume: arn:aws:iam::481665099346:role/cloudfence

      - name: List files in S3 bucket
        run: aws s3 ls outsider-oidc-demo-bucket
